name: movie
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.3.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  cached_network_image: ^3.3.1
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_rating_bar: ^4.0.1
  http: ^1.2.1
  sqflite: ^2.3.2

  core:
    path: ../core
  search:
    path: ../search

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  bloc_test: ^9.1.7
  build_runner: ^2.4.8
  mockito: ^5.4.4

flutter:

