name: ditonton
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  get_it: ^7.6.7
  flutter_bloc: ^8.1.5

  about:
    path: packages/about
  core:
    path: packages/core
  movie:
    path: packages/movie
  search:
    path: packages/search
  tv_series:
    path: packages/tv_series

  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true
  assets:
    - certificate/
    - assets/