// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9ww_EvFeQECT6agIgSoCNiGEXk-s7VDk',
    appId: '1:997038112535:web:c69f6e4f46d1ae75d40152',
    messagingSenderId: '997038112535',
    projectId: 'ditonton2-5ba87',
    authDomain: 'ditonton2-5ba87.firebaseapp.com',
    storageBucket: 'ditonton2-5ba87.appspot.com',
    measurementId: 'G-YEWM6Q0SR7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFvFAXsH1o2anG16jPQ98MXuLWsN49lzk',
    appId: '1:997038112535:android:db50aae7aa3310f5d40152',
    messagingSenderId: '997038112535',
    projectId: 'ditonton2-5ba87',
    storageBucket: 'ditonton2-5ba87.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqQ2QtedN5VuTl3U_aqE2vuxJF3iK11mQ',
    appId: '1:997038112535:ios:220c5e221abcaf3cd40152',
    messagingSenderId: '997038112535',
    projectId: 'ditonton2-5ba87',
    storageBucket: 'ditonton2-5ba87.appspot.com',
    iosBundleId: 'com.dicoding.ditonton',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqQ2QtedN5VuTl3U_aqE2vuxJF3iK11mQ',
    appId: '1:997038112535:ios:f60dd45f7e964216d40152',
    messagingSenderId: '997038112535',
    projectId: 'ditonton2-5ba87',
    storageBucket: 'ditonton2-5ba87.appspot.com',
    iosBundleId: 'com.dicoding.ditonton.RunnerTests',
  );
}
