name: search
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.3.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  rxdart: ^0.27.7

  core:
    path: ../core

  movie:
    path: ../movie

  tv_series:
    path: ../tv_series

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  bloc_test: ^9.1.7
  build_runner: ^2.4.8
  mockito: ^5.4.4

flutter:

